{
 "title": "AI Project One",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * (\n  sum(rate(container_cpu_usage_seconds_total{namespace=\"ai-sre\",container=\"fake-infer\"}[2m]))\n  /\n  clamp_min(\n    sum(rate(http_requests_total{job=\"fake-infer\",path=\"/infer\"}[2m])),\n    1e-9\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS (requests per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"fake-infer\", path=\"/infer\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_requests_total{job=\"fake-infer\",path=\"/infer\",status=~\"5..\"}[5m]))\n  /\n  clamp_min(sum(rate(http_requests_total{job=\"fake-infer\",path=\"/infer\"}[5m])),1e-9)\n) / 0.01    # 0.01 = 1 % budget for a 99 % SLO",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (rate(http_request_duration_seconds_bucket{job=\"fake-infer\", path=\"/infer\"}[5m]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  (sum(rate(http_requests_total{job=\"fake-infer\",path=\"/infer\",status=~\"5..\"}[5m])) or vector(0))\n  /\n  clamp_min((sum(rate(http_requests_total{job=\"fake-infer\",path=\"/infer\"}[5m])) or vector(0)), 1e-9)\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}